FROM node:22-alpine AS builder

COPY chayns-led-gateway /opt/chayns-led-gateway

WORKDIR /opt/chayns-led-gateway

RUN npm install

RUN npm run build

FROM nginx:alpine

RUN mkdir -p /var/www/app

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /opt/chayns-led-gateway/build/ /usr/share/nginx/html/

EXPOSE 2000

CMD ["nginx", "-g", "daemon off;"]