server {
    listen 2000;
    server_name venhoff.org;

    return 301 https://$host:2443$request_uri;
}

server {
    listen 2443 ssl;
    server_name venhoff.org;

    ssl_certificate     /etc/letsencrypt/live/venhoff.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/venhoff.org/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
